language: go

sudo: required

go:
  - "1.10.x"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - make deps

before_script:
  - go get -u golang.org/x/tools/cmd/goimports
  - make assets
#  - go get -u github.com/golang/lint/golint

script:
  - go vet ./...
  - make

#  - diff <(goimports -d .) <(printf "")
#  - diff <(golint ./...) <(printf "")