language: go

go:
  - "1.10.x"

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install:
  - go get -t ./...
  - make deps

before_script:
  - go get -u golang.org/x/tools/cmd/goimports
#  - go get -u github.com/golang/lint/golint

script:
  - go vet ./...
  - make

#  - diff <(goimports -d .) <(printf "")
#  - diff <(golint ./...) <(printf "")