language: go

go:
  - "1.10.x"

install:
  - go get -t ./...

before_script:
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/dep/cmd/dep
#  - go get -u github.com/golang/lint/golint

script:
  - make deps
  - go vet ./...
  - make

#  - diff <(goimports -d .) <(printf "")
#  - diff <(golint ./...) <(printf "")